networks:
  storage:

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PGID=${MEDIA_PGID}
      - TZ=${TZ}
    volumes:
      - /lake/syncthing/config:/config
      - /lake/media/books:/data/books
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    labels:
      - traefik.enable=true
      - traefik.docker.network=storage
      - traefik.http.routers.syncthing.rule=Host(`syncthing.${DOMAIN}`)
      - traefik.http.services.syncthing.loadbalancer.server.port=8384
    restart: unless-stopped
    networks:
      - storage
